name: Build Android APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: JDK 17 kurulumu
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle önbelleği
        uses: gradle/actions/setup-gradle@v3

      - name: APK üret
        run: ./gradlew assembleDebug

      - name: APK'yı artifact olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
